feat(prettier): add prettier options
project-error/fivem-react-boilerplate-lua pull request #74
Opened 2022-08-10 13:59 UTC by GitScorz

_I'm adding prettier options, because nowadays almost everybody uses Prettier._

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open for the same update/change?
* [x] Have you built and tested the `resource` in-game after the relevant change?

2022-08-20 22:30 UTC, itschip requested changes

2022-08-20 22:30 UTC, itschip commented on .prettierrc
> +  "singleQuote": true,
Please add double quotes for jsx :P

2022-08-20 22:36 UTC, itschip approved these changes

2022-08-22 23:26 UTC, TasoOneAsia requested changes
Prettier hasn't been added to the devDependencies. If we're going to include a prettier config by default, then we should probably add it as a package 😛

2022-09-07 08:51 UTC, itschip approved these changes

2022-10-09 10:33 UTC, itschip commented
@GitScorz Please rebase

2022-11-19 19:41 UTC, closed without merging